id = "common-lisp"
name = "Common Lisp"
version = "0.5.2"
schema_version = 1
authors = ["Victor Zhuk"]
description = "Common Lisp and Lispico language support for Zed"
repository = "https://github.com/victorzhuk/zed-lisp"
snippets = ["snippets/lispico clojure.json", "snippets/lispico cl.json"]

[grammars.commonlisp]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-commonlisp"
commit = "32323509b3d9fe96607d151c2da2c9009eb13a2f"

[grammars.clojure]
repository = "https://github.com/sogaiu/tree-sitter-clojure"
commit = "e43eff80d17cf34852dcd92ca5e6986d23a7040f"

[language_servers.sextant]
name = "sextant"
languages = ["Common Lisp"]

[language_servers.lispico]
name = "lispico"
languages = ["Lispico Clojure", "Lispico CL"]
